#pragma once

//From GLFW/include/GLFW/glfw3.h
#define MSSHI_MOUSE_BUTTON_1         0
#define MSSHI_MOUSE_BUTTON_2         1
#define MSSHI_MOUSE_BUTTON_3         2
#define MSSHI_MOUSE_BUTTON_4         3
#define MSSHI_MOUSE_BUTTON_5         4
#define MSSHI_MOUSE_BUTTON_6         5
#define MSSHI_MOUSE_BUTTON_7         6
#define MSSHI_MOUSE_BUTTON_8         7
#define MSSHI_MOUSE_BUTTON_LAST      MSSHI_MOUSE_BUTTON_8
#define MSSHI_MOUSE_BUTTON_LEFT      MSSHI_MOUSE_BUTTON_1
#define MSSHI_MOUSE_BUTTON_RIGHT     MSSHI_MOUSE_BUTTON_2
#define MSSHI_MOUSE_BUTTON_MIDDLE    MSSHI_MOUSE_BUTTON_3
